services:
  mediamtx:
    image: bluenviron/mediamtx:1
    container_name: mediamtx
    environment:
      MTX_RTSPTRANSPORTS: tcp
    ports:
      - "8554:8554"
      - "8888:8888"
  
  ffmpeg-generator:
    depends_on:
      - mediamtx
    image: lscr.io/linuxserver/ffmpeg:8.0.1
    container_name: ffmpeg-generator
    command: >
      -re
      -f lavfi
      -i testsrc=size=1280x720:rate=30
      -vf "drawtext=text='stream=camera_sync_test':x=20:y=20:fontsize=30:fontcolor=white:box=1:boxcolor=black,
          drawtext=text='frame=%{n} | pts=%{pts\\:hms} | fps=30':x=20:y=60:fontsize=30:fontcolor=white:box=1:boxcolor=black"
      -c:v libx264
      -preset veryfast
      -tune zerolatency
      -pix_fmt yuv420p
      -f rtsp
      rtsp://mediamtx:8554/camera_sync_test

  display-client:
    build: ./display-client
    container_name: display-client
    ports:
      - "3000:3000"
    depends_on:
      - mediamtx
  
  orchestration-api:
    build: ./streaming-lab-orchestration-api
    container_name: orchestration-api
    ports:
      - "8080:8080"
    depends_on:
      - mediamtx