name: Auto approve

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.user.login == 'doikenichi'
    steps:
      - uses: hmarr/auto-approve-action@v4
